### PR TITLE
Add guide to code checking with GitHub

### PR DESCRIPTION
**Pull request by matthew-white**
Let's write a guide about code checking with Github. Where useful, we'll touch on general advice about code checking, but in general, we'll focus on the GitHub specifics.
- [x] ~~Incorporate guidelines from Sana's code check guidelines.~~
- [x] Solo code checks with GitHub
  - [x] Commit every file rather than every directory. (Maria's advice) (Moved to #10.)
- [x] Collaborative code checks with GitHub
  - [x] Issues
  - [x] In-line comments
    - Don't use for substantive discussion: put that in issues.
  - [x] Iterative code checks
    - Review new commits.
  - [x] Option 1. Don't branch, don't fork: just add issues and in-line comments.
    - Checker needs read/write access.
    - Put in-line comments on the master branch.
    - Problems with in-line comments: hard to access or search.
    - Linking to a file or a line: use stable version (press `y`).
    - Downloading list of in-line comments
  - [x] Option 2. Branch, but don't fork.
    - Checker can commit to master branch as long as checkee agrees and checks the checker's work.
    - Pull requests (brief)
    - Temporary changes so you can keep going; then merge stable version into your branch.
      - Review new commits before merging them into your temporary branch.
  - [x] Option 3. Fork. Let's not go in-depth here, but instead just add links to external resources.
    - What it is
    - Benefits
    - Why we don't do it

### CODE REVIEW

**Comment by matthew-white** [comment]
@mdieci @shweeneypeas @edegnan Harrison and I want to write a guide to code checking using GitHub. Do you have any tips/best practices you've uncovered? Anything you did that went especially well or especially badly? Experiences as the checker or checkee are both useful!

**Comment by mdieci** [comment]
I worked by myself on a code-check, and I had many different do-files that corresponded to different stages of cleaning several modules (ie stage1_module1.do, stage2_module1.do, stage1_module2.do, etc.). What was helpful (and I didn't start off doing this) was to commit every time I completed the code-check on one of the dofiles and note the changes I made in the commit message. That way, it was easy to cross-check dofiles for the same module/stage of cleaning across survey rounds. The changes that I had made to one round likely applied to another, and this way they were easy to see and implement. What I had done prior was to check all of the dofiles in a particular subfolder (ie. round1/stage1/...) and then commit. This was perhaps more efficient in the moment, but then I had to do some digging to find the changes I made to individual files (so in the end, I didn't save time).

**Comment by matthew-white** [comment]
Thanks @mdieci! I've added that to the outline above. CC @hdiamondpollock, who's writing the first draft.

**Comment by shweeneypeas** [comment]
Sorry I didn't respond to this earlier -- I've never done a codecheck on
GitHub so unfortunately I don't think I have much to offer. I'd be happy to
look over the draft you put together though.

On Thu, Jan 22, 2015 at 12:14 PM, Matthew White <notifications@github.com>
wrote:

> Thanks @mdieci <https://github.com/mdieci>! I've added that to the
> outline above. CC @hdiamondpollock <https://github.com/hdiamondpollock>,
> who's writing the first draft.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PovertyAction/github-training/pull/8#issuecomment-71057928>
> .
>



-- 

Martin Sweeney | Research Analyst | Innovations for Poverty Action
msweeney@poverty-action.org | Skype martindsweeney | +1-908-447-4199

**Comment by matthew-white** [comment]
Thanks @shweeneypeas! @edegnan, any thoughts on this?

**Comment by matthew-white** [comment]
Harrison writes:

> - I addressed most of the issues you've laid out in the checklist, but wasn't sure what to incorporate from Sana's guidelines / Maria's feedback. Also forgot what an 'iterative' code check was. 
> - I'm not 100% on some of what I put in the guide and whether some of it needs additional explanation. I linked to examples/resources in many cases where more information was available, but I'm unsure if that should be done more or how much more should be explained in the guide itself.

**Pull request merged**
